install: carthage update --cache-builds --platform iOS
language: swift
os: osx
osx_image: xcode11.3
script:
  xcodebuild -scheme SwiftDiscogs -project SwiftDiscogs.xcodeproj -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 11,OS=13.3' test
after_success:
  bash <(curl -s https://codecov.io/bash)

